### ISSUE TITLE
hubot-slack v4 has broken hackbot

### ISSUE THREAD

**Issue by Codesleuth** [TechNottingham/Hackbot#29]
The `hubot-hackbot` script fails now that brain data is not being updated.

See: slackhq/hubot-slack#326

This can be fixed by using the slack client memory data store to get user information. An example of this can be seen in TechNottingham/hubot-hackbot#9

The fix belongs in the hackbot script, and not this repo, and will be connected other there.

**Comment by nick599** [comment]
Since https://github.com/TechNottingham/hubot-hackbot/issues/9 is now closed, does this affect this?

**Comment by Codesleuth** [comment]
This is unrelated to that. This issue was closed a while ago actually, in a huge piece of work I did last year.
